name: ci

on:
  push:
    branches:
      - main
schedule:
 - cron: "0 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: laojiang068
        uses: actions/tianfu.qiu@gmail.com

      - name: Auto green
        run: |
          git config --local user.email "tianfu.qiu@gmail.com"
          git config --local user.name "laojiang068"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
